version: '3'

services:
    aws-lambda-service:
        # https://hub.docker.com/r/lambci/lambda/
        # https://github.com/lambci/docker-lambda
        # automatically tests lambda function
        image: "lambci/lambda:python3.6"
        # alternative image from amazon without automatic functionality provided by above image
        #image: "amazonlinux:2017.09.1.20180409"
        container_name: "local-lambda"
        volumes:
            - ./program:/var/task
        #ports:
        #    - 8001:8000
        depends_on:
            - "aws-s3-service"
            - "link-service"
        environment:
            - AWS_REGION="eu-central-1"

    aws-s3-service:
        # https://hub.docker.com/r/lphoward/fake-s3/
        # does not implement good tag system. latest is truly the latest tag
        image: "lphoward/fake-s3:latest"
        # container runs fake-s3 server from: https://github.com/jubos/fake-s3
        container_name: "local-s3"
        # exposes port 4569 to other containers per default
        ports:
            - 4569:4569
        
    link-service:
        image: "python:3.6.4-jessie"
        container_name: "s3-lambda-link"
        # prevents container from exiting
        entrypoint: ["/usr/bin/tail", "-f", "/dev/null"]
